/// Flutter icons CrabCalc
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CrabCalc
///      fonts:
///       - asset: fonts/CrabCalc.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CrabCalcIcons {
  CrabCalcIcons._();

  static const _kFontFam = 'CrabCalc';
  static const _kFontPkg = null;

  static const IconData crab_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
